language: python
python:
  - "2.7"
script: 
  PYTHONPATH=./ coverage run --source=stringtree py.test
script:
  - py.test coveralls/tests.py --doctest-modules -v --cov coveralls --cov-report term-missing
after_success:
  coveralls